// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue"
import { defineSliceZoneComponents } from "@prismicio/vue"

export const components = defineSliceZoneComponents({
  page_hero: defineAsyncComponent(() => import("./PageHero/index.vue"))
})
