export default {
	MAILCHIMP_KEY: process.env.MAILCHIMP_KEY,
	MAILCHIMP_LIST_ID: process.env.MAILCHIMP_LIST_ID,
	MAILCHIMP_LOCALE: process.env.MAILCHIMP_LOCALE,

	MANDRILL_KEY: process.env.MANDRILL_KEY,
	MANDRILL_SENDER: process.env.MANDRILL_SENDER,
	MANDRILL_SENDER_NAME: process.env.MANDRILL_SENDER_NAME,
	MANDRILL_RECEIVER: process.env.MANDRILL_RECEIVER
}
